requirements:
  # Requirements.txt contains nothing.
  - requirements/requirements.txt:
      update: False
      pin: False
  - requirements/requirements_synapse.txt:
      update: all
      pin: True
  - requirements/requirements_dev.txt:
      update: all
      pin: True
  - requirements/requirements_dep.txt:
      update: all
      pin: True
  - requirements/requirements_37.txt:
      update: all
      pin: True
  - requirements/requirements_38.txt:
      update: all
      pin: True
  - requirements/requirements_39.txt:
      update: all
      pin: True